[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "music-rec-system"
version = "0.1.0"
description = "Music recommendation system"
requires-python = ">=3.8" 